apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo:latest
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumes:
    - name: mongo-data
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo # This matches the label on the pod
  ports:
    - protocol: TCP
      port: 27017 # The port the MongoDB container is listening on
      targetPort: 27017 # Port on the pod to forward traffic to
      nodePort: 30017 # The external port accessible from localhost
  type: NodePort # Expose the service on a NodePort
